version: "3"
services:
    api:
      build: .
      depends_on:
          - postgres
      ports: 
          - 8000:8000
      volumes:
          - ./:/usr/src/app:ro
      environment:
          - DATABASE_HOSTNAME=postgres
          - DATABASE_PORT=5432
          - DATABASE_PASSWORD=password123
          - DATABASE_NAME=fastapi
          - DATABASE_USERNAME=postgres
          - SECRET_KEY=1c23b1feabcf4a30e7fe40c8e581f0724836aaead3062d5c13a486b9a0060b23
          - ALGORITHM=HS256
          - ACCESS_TOKEN_EXPIRES_MINUTES=60
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload && alembic upgrade head
    postgres:
      image: postgres
      environment:
          - POSTGRES_PASSWORD=password123
          - POSTGRES_DB=fastapi
      volumes:
          - postgres-db:/var/lib/postgresql/data
volumes:
   postgres-db:
